version: '3.8'
services:
  postgres-user:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data

  postgres-post:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: post_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-post-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres-user
      - rabbitmq

  post-service:
    build:
      context: .
      dockerfile: apps/post-service/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres-post

  analyst-service:
    build:
      context: .
      dockerfile: apps/analyst-service/Dockerfile
    depends_on:
      - redis
      - user-service
      - post-service

volumes:
  postgres-user-data:
  postgres-post-data:
